source 'https://rubygems.org'
ruby '2.2.1'

gem 'aescrypt'
gem 'activerecord'
gem 'aws-sdk', '~> 1.8.1.2'
gem 'bcrypt', '~> 3.1.7'
gem 'figaro'
gem 'mini_magick'
gem 'pg'
gem 'puma'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'tux'
